# Generated by Django 5.0.7 on 2026-01-29 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('dimension', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding Model',
                'verbose_name_plural': 'Embedding Models',
                'db_table': 'embedding_models',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('vector_id', models.CharField(max_length=255)),
                ('dimension', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='documents.documentchunk')),
            ],
            options={
                'verbose_name': 'Embedding Record',
                'verbose_name_plural': 'Embedding Records',
                'db_table': 'embedding_records',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('results_count', models.IntegerField(default=0)),
                ('search_time_ms', models.IntegerField(default=0)),
                ('document_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
