# Generated by Django 4.2.28 on 2026-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT')], max_length=255),
        ),
    ]
