# Generated by Django 5.0.7 on 2026-02-27 08:26

import cloudinary_storage.storage
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=documents.models.document_upload_path,
            ),
        ),
    ]
